### ISSUE TITLE
should the selection of miniconda version be configurable?

### ISSUE THREAD

**Issue by vjcitn** [LTLA/basilisk.utils#4]
https://github.com/LTLA/basilisk.utils/blob/ea7cb0cf182e283ea397c2300dbbd086e6faa584/R/installConda.R#L97 hard codes it.

FWIW manually changing to the latest worked OK for an updated BiocSklearn installation.

**Comment by LTLA** [comment]
Not by the client package developer. **basilisk** only manages a single version of miniconda for a given installation. If it were to be configured, it would need to be managed at **basilisk**'s level, probably via environment variables.

I recently thought about updating it to a newer version to support M1 macs, but this is likely to have ramifications for all **basilisk** clients. Some coordination with downstream packages would be required.

**Comment by LTLA** [comment]
FYI it seems that it can be configured via the `BASILISK_MINICONDA_VERSION` environment variable.
